FROM oven/bun:debian

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    git && \
    apt-get auto-remove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* && \
    chsh -s $(which bash) bun

RUN ln -s /usr/local/bin/bun /usr/local/bin/node

USER bun
ENV PATH="~/.bun/bin:${PATH}"
